# Auto-generated by FlavorLab webapp — do not edit manually
# Structure: name, sensory_scores (sweet/sour/bitter/umami/salty 0-100),
#            confidence (0.0-1.0), evidence (string), source_url (string or None)
predicted_ingredients = [
]
